version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lapesFI
    ports:
      - '4000:4000'
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "npm run knex:migrate && npm run start"

  db:
    image: postgres:14.8
    restart: "always"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: lapesfi
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
