version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lapesFI
    ports:
      - '4000:4000'
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: lapesfi
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
